= PythonTools
Kaspar Johannes Schneider <kaspar.sch@outlook.com>
:description: A collection of tools for Python that I created for my personal use.
:setanchors:
:toc: macro
:toclevels: 2
:sectnums:
:source-highlighter: rouge

image:https://github.com/KasparJohannesSchneider/PythonTools/actions/workflows/test.yml/badge.svg[link=https://github.com/KasparJohannesSchneider/PythonTools/actions/workflows/test.yml]
image:https://github.com/KasparJohannesSchneider/PythonTools/actions/workflows/doc.yml/badge.svg[link=https://github.com/KasparJohannesSchneider/PythonTools/actions/workflows/doc.yml]
image:https://codecov.io/gh/KasparJohannesSchneider/PythonTools/branch/main/graph/badge.svg?token=262M3tABG3[link=https://codecov.io/gh/KasparJohannesSchneider/PythonTools]
image:https://img.shields.io/lgtm/grade/python/g/KasparJohannesSchneider/PythonTools.svg?logo=lgtm&logoWidth=18[link=https://lgtm.com/projects/g/KasparJohannesSchneider/PythonTools/alerts]
image:https://img.shields.io/lgtm/alerts/g/KasparJohannesSchneider/PythonTools.svg?logo=lgtm&logoWidth=18[link=https://lgtm.com/projects/g/KasparJohannesSchneider/PythonTools/alerts]
image:https://img.shields.io/badge/License-MIT-green.svg[link=https://github.com/KasparJohannesSchneider/PythonTools/blob/main/LICENSE]
image:https://img.shields.io/badge/Language-Python_3.7-blue.svg[link=https://www.python.org/]

A collection of tools for Python that I created for my personal use.

toc::[]

== File Structure
[source, bash]
----
│   .gitignore
│   LICENSE
│   README.adoc
│   README.pdf
│
├───.github                     # GitHub CI
│   └───workflows
│           dependencies.txt    # Dependencies for unit tests
│           doc.yml             # Convert README to PDF
│           test.yml            # Run unit tests and coverage
│
├───python_tools                # Python package
│       debug_tools.py
│       math_tools.py
│       __init__.py
│
└───test                        # Package containing unit tests
        test_debug_tools.py
        test_math_tools.py
        __init__.py

----

== Import
[source, python]
----
import python_tools as pt
----

== Debug Tools
Tools that can be used for debugging.

=== Debug Wrapper `@debug`
A debug wrapper that prints some useful information about a function call.

==== How to use
This wrapper can be used by placing the corresponding decorator above the declaration of the function.
[source, python]
----
import python_tools as pt


@pt.debug
def a_function(x, y, z):
  pass
----

==== Expected output
----
--debug--debug--debug--debug--debug--debug--debug--debug--debug--debug--
--  Function: a_function(x, y, z)
--  Arguments: (1, 2, 3)
--  Returned: None
--  Time elapsed [s]: 0.0
--debug--debug--debug--debug--debug--debug--debug--debug--debug--debug--
----

=== Timer Wrapper `@timer`
==== How to use
This wrapper can be used by placing the corresponding decorator above the declaration of the function.
[source,python]
----
import python_tools as pt


@pt.timer
def a_function(x, y, z):
  pass
----

==== Expected output

----
--timer--timer--timer--timer--timer--timer--timer--timer--timer--timer--
--  Function: a_function(x, y, z)
--  Time elapsed [s]: 0.0
--timer--timer--timer--timer--timer--timer--timer--timer--timer--timer--
----

=== Run Function and get STDOUT `run_fct_get_stdout(fct: callable, *args) -> str:`

Runs a function and collects stdout during the execution of said function and returns the collected stdout as a string.

==== How to use

[source,python]
----
>>> import python_tools as pt
>>> pt.run_fct_get_stdout(print, 'Hello world!')
'Hello world!\n'
----

== Math Tools
Tools related to mathematics

=== Sum from 1 to n `sum_1_n(n: int) -> int`
This function calculates the sum of all numbers from 1 to `n`.

https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF[Wikipedia: 1 + 2 + 3 + 4 + ⋯]

==== Example
[source,python]
----
>>> import python_tools as pt
>>> pt.sum_1_n(10)
55
----

=== Lower Triangular Number `ltm(n: int) -> int`
This function returns `n` if it is a triangular number, or the next lower triangular number.

https://en.wikipedia.org/wiki/Triangular_number[Wikipedia: Triangular number
]

==== Example
[source, python]
----
>>> import python_tools as pt
>>> pt.ltm(16)
15
----

=== Is Triangular? `is_triangular(n: int) -> bool`
This function checks if a number is triangular.

https://en.wikipedia.org/wiki/Triangular_number[Wikipedia: Triangular number
]

==== Example
[source, python]
----
>>> import python_tools as pt
>>> pt.is_triangular(15)
True
>>> pt.is_triangular(16)
False
>>> pt.is_triangular(21)
True
----

== Web Tools
Tools related to the internet and webpages.

=== Is Page up `is_page_up(url: str) -> bool`
Tests if a webpage is up (returns 200).

==== Example
[source, python]
----
# Test an existing url
>>> pt.is_page_up('https://www.twitter.com/')
True

# Test an url that doesn't exist
>>> pt.is_page_up('https://www.a1s2d3e5f2c5e4d2f5r1e23c5e1.com/')
False
----