
name: Documentation to PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
          
      # Install Asciidoctor
      - name: Install Asciidoctor
        run: |
          sudo gem install asciidoctor-pdf
          sudo gem install rouge
      
      # Remove Images from the Internet
      - name: Remove Images from the Internet
        run: |
          SRC="image:http.*"
          RPL=""
          sed -i "s/$SRC/$RPL/" README.adoc
          echo | cat README.adoc
          
      # Build PDF
      - name: Build the PDF
        run: |
          asciidoctor-pdf README.adoc
          
      # Commit the documentation
      - name: Commit README.pdf
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add README.pdf
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "[bot] updated README.pdf"
             echo "::set-output name=push::true"
          fi
        shell: bash
      
      # Push the commit
      - name: Push Commit
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.SECRET_TOKEN }}
