
name: Documentation to PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
          
      # Install Asciidoctor
      - name: Install Asciidoctor
        run: |
          gem install asciidoctor-pdf
          gem install rouge
          
      # Build PDF
      - name: Build the PDF
        run: |
          asciidoctor-pdf README.adoc
          ls
